[project]
name = "blokus-ui"
version = "0.1.0"
description = "Blokus Arena web app, built with Gradio"
authors = [
    { name = "Ze Wang", email = "zewang@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "blokus",
    "gradio>=6.28.0",
    "python-dotenv>=1.2.3",
]

[project.scripts]
blokus = "blokus_ui:main"

[tool.uv.sources]
blokus = { workspace = true }

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
